Number_of_manutans='3'		#Must be an integer
Sex='Mevr.'			#Dhr. or Mevr.
Company_name='Test'	
Street_adres='Bot'
Street_number='12'
Street_adjective='B'
Initials='B.O.T.'
Zip_code='1212'
City='xxxx'
Surname='Foo'
